### ISSUE TITLE
AWS SAA Reading Checklist

### ISSUE THREAD

**Issue by obrignoni** [obrignoni/obrignoni.github.io#1]
### 390 AWS Practice Exam Questions with Answers, Links & detailed Explanations
by Neal Davis

The managed service includes hardware provisioning, database setup, patching and backups.

Questions
- [x] What is ConsumedLCUs metric in CloudWatch? = You are charged for each hour or partial hour that a Network Load Balancer is running and the number of Load Balancer Capacity Units (LCU) used by Network Load Balancer per hour.

Digital Cloud References
------------
- [ ] https://digitalcloud.training/2018/10/19/cloud-computing-basics-compute/
- [ ] https://digitalcloud.training/aws-iam/
- [ ] https://digitalcloud.training/amazon-aurora/
- [ ] https://digitalcloud.training/amazon-cloudfront/
- [ ] https://digitalcloud.training/amazon-cloudwatch/
- [ ] https://digitalcloud.training/amazon-dynamodb/
- [x] https://digitalcloud.training/amazon-ebs/
- [ ] https://digitalcloud.training/amazon-ec2/
- [ ] https://digitalcloud.training/amazon-ec2-auto-scaling/
- [ ] https://digitalcloud.training/amazon-ecs-and-eks/
- [ ] https://digitalcloud.training/amazon-efs/
- [ ] https://digitalcloud.training/amazon-fsx/
- [x] https://digitalcloud.training/amazon-kinesis/
- [ ] https://digitalcloud.training/amazon-rds/
- [ ] https://digitalcloud.training/amazon-route-53/
- [ ] https://digitalcloud.training/amazon-s3-and-glacier/
- [ ] https://digitalcloud.training/amazon-vpc/
- [ ] https://digitalcloud.training/aws-application-integration-services/
- [x] https://digitalcloud.training/aws-elastic-load-balancing-aws-elb/
- [x] https://digitalcloud.training/aws-global-accelerator/
- [ ] https://digitalcloud.training/aws-lambda/
- [x] https://digitalcloud.training/aws-organizations/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/additional-aws-services-tools/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/architecting-for-the-cloud/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/aws-analytics/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/aws-billing-and-pricing/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/aws-cloud-management/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/aws-compute/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/aws-databases/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/aws-global-infrastructure/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/aws-shared-responsibility-model/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/aws-storage/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/aws-networking/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/cloud-computing-concepts/
- [x] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/cloud-security/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/content-delivery-and-dns-services/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/elastic-load-balancing-and-auto-scaling/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/identity-and-access-management/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/management-governance/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/monitoring-and-logging-services/
- [ ] https://digitalcloud.training/certification-training/aws-certified-cloud-practitioner/notification-services/

FAQs
- [ ] VPC - https://aws.amazon.com/vpc/faqs/

AWS Reference
-----
- [ ] https://aws.amazon.com/architecture/
- [ ] https://aws.amazon.com/autoscaling/
- [ ] https://aws.amazon.com/about-aws/global-infrastructure/
- [ ] https://aws.amazon.com/about-aws/global-infrastructure/regions_az/ 
- [x] https://aws.amazon.com/about-aws/whats-new/2017/08/amazon-virtual-private-cloud-vpc-now-allows-customers-to-expand-their-existing-vpcs/
- [ ] https://aws.amazon.com/about-aws/whats-new/2017/10/announcing-amazon-ec2-per-second-billing/
- [x] https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-virtual-private-clouds-can-now-be-shared-with-other-aws-accounts/
- [ ] https://aws.amazon.com/architecture/well-architected/ 
- [x] https://aws.amazon.com/artifact/
- [ ] https://aws.amazon.com/aws-cost-management/
- [ ] https://aws.amazon.com/aws-cost-management/aws-budgets/ 
- [ ] https://aws.amazon.com/aws-cost-management/aws-cost-explorer/ 
- [ ] https://aws.amazon.com/aws-cost-management/aws-cost-optimization/  
- [ ] https://aws.amazon.com/aws-cost-management/aws-cost-optimization/right-sizing/
- [ ] https://aws.amazon.com/batch/
- [ ] https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/
- [ ] https://aws.amazon.com/blogs/apn/the-6-pillars-of-the-aws-well-architected-framework/
- [ ] https://aws.amazon.com/blogs/architecture/tag/scalability/
- [ ] https://aws.amazon.com/blogs/networking-and-content-delivery/vpc-sharing-a-new-approach-to-multiple-accounts-and-vpc-management/
- [ ] https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-continuous-backups-and-point-in-time-recovery-pitr/
- [ ] https://aws.amazon.com/blogs/aws/new-per-second-billing-for-ec2-instances-and-ebs-volumes/
- [ ] https://aws.amazon.com/blogs/aws/new-server-side-encryption-for-amazon-simple-queue-service-sqs/
- [ ] https://aws.amazon.com/blogs/security/how-to-automatically-update-your-security-groups-for-amazon-cloudfront-and-aws-waf-by-using-aws-lambda/
- [x] https://aws.amazon.com/blogs/security/how-to-create-a-policy-that-whitelists-access-to-sensitive-amazon-s3-buckets/
- [ ] https://aws.amazon.com/blogs/security/how-to-restrict-amazon-s3-bucket-access-to-a-specific-iam-role/
- [ ] https://aws.amazon.com/blogs/security/how-to-use-aws-organizations-to-automate-end-to-end-account-creation/
- [ ] https://aws.amazon.com/cloudformation/
- [x] https://aws.amazon.com/cognito/
- [ ] https://aws.amazon.com/codecommit/features/
- [ ] https://aws.amazon.com/cdk/
- [ ] https://aws.amazon.com/cloudformation/
- [ ] https://aws.amazon.com/cloudfront/
- [ ] https://aws.amazon.com/cloudfront/faqs/
- [ ] https://aws.amazon.com/cloudfront/streaming/
- [x] https://aws.amazon.com/cloudhsm/
- [x] https://aws.amazon.com/cloudhsm/features/
- [ ] https://aws.amazon.com/cloudtrail/
- [ ] https://aws.amazon.com/cloudwatch/
- [ ] https://aws.amazon.com/cloudwatch/features/
- [x] https://aws.amazon.com/compliance/hipaa-compliance/
- [x] https://aws.amazon.com/compliance/programs/
- [x] https://aws.amazon.com/compliance/shared-responsibility-model/
- [ ] https://aws.amazon.com/codecommit/
- [ ] https://aws.amazon.com/datasync/faqs/
- [x] https://aws.amazon.com/directconnect/faqs/
- [ ] https://aws.amazon.com/directconnect/
- [x] https://aws.amazon.com/dms/ 
- [ ] https://aws.amazon.com/dynamodb/
- [ ] https://aws.amazon.com/dynamodb/dax/
- [x] https://aws.amazon.com/ebs/
- [ ] https://aws.amazon.com/ec2/
- [x] https://aws.amazon.com/ec2/autoscaling/
- [ ] https://aws.amazon.com/ec2/dedicated-hosts/
- [ ] https://aws.amazon.com/ec2/pricing/reserved-instances/
- [ ] https://aws.amazon.com/ec2/spot/
- [ ] https://aws.amazon.com/ecr/
- [ ] https://aws.amazon.com/ecs/
- [ ] https://aws.amazon.com/efs/
- [ ] https://aws.amazon.com/elasticache/
- [ ] https://aws.amazon.com/elasticbeanstalk/
- [ ] https://aws.amazon.com/elasticloadbalancing/
- [ ] https://aws.amazon.com/elastictranscoder/
- [ ] https://aws.amazon.com/emr/
- [x] https://aws.amazon.com/fsx/lustre/faqs
- [ ] https://aws.amazon.com/glacier/pricing/
- [ ] https://aws.amazon.com/global-accelerator/
- [ ] https://aws.amazon.com/glue/
- [x] https://aws.amazon.com/guardduty/
- [ ] https://aws.amazon.com/iam/faqs/
- [ ] https://aws.amazon.com/iam/identity-center/faqs/
- [x] https://aws.amazon.com/inspector/
- [ ] https://aws.amazon.com/iot-core/
- [x] https://aws.amazon.com/kms/
- [ ] https://aws.amazon.com/lambda/
- [ ] https://aws.amazon.com/lambda/edge/
- [ ] https://aws.amazon.com/lambda/features/
- [ ] https://aws.amazon.com/lightsail/features/
- [ ] https://aws.amazon.com/managed-services/
- [ ] https://aws.amazon.com/macie/
- [ ] https://aws.amazon.com/neptune/
- [ ] https://aws.amazon.com/opsworks/
- [ ] https://aws.amazon.com/organizations/
- [ ] https://aws.amazon.com/outposts/
- [ ] https://aws.amazon.com/premiumsupport/features/
- [x] https://aws.amazon.com/premiumsupport/knowledge-center/connect-s3-vpc-endpoint/
- [ ] https://aws.amazon.com/premiumsupport/knowledge-center/ebs-automatic-encryption/
- [ ] https://aws.amazon.com/premiumsupport/knowledge-center/instance-store-vs-ebs/
- [ ] https://aws.amazon.com/premiumsupport/knowledge-center/report-aws-abuse/ 
- [ ] https://aws.amazon.com/premiumsupport/knowledge-center/secure-s3-resources/
- [ ] https://aws.amazon.com/premiumsupport/plans/
- [ ] https://aws.amazon.com/premiumsupport/technology/personal-health-dashboard/
- [ ] https://aws.amazon.com/premiumsupport/technology/trusted-advisor/
- [ ] https://aws.amazon.com/premiumsupport/technology/trusted-advisor/best-practice-checklist/
- [ ] https://aws.amazon.com/pricing/
- [x] https://aws.amazon.com/privatelink/
- [ ] https://aws.amazon.com/quicksight/
- [ ] https://aws.amazon.com/quickstart/
- [ ] https://aws.amazon.com/redshift/
- [ ] https://aws.amazon.com/rekognition/image-features/
- [ ] https://aws.amazon.com/rds/
- [ ] https://aws.amazon.com/rds/aurora/faqs/
- [ ] https://aws.amazon.com/rds/aurora/mysql-features/ 
- [ ] https://aws.amazon.com/rds/features/
- [ ] https://aws.amazon.com/rds/features/multi-az/
- [ ] https://aws.amazon.com/route53/
- [ ] https://aws.amazon.com/s3/faqs/
- [ ] https://aws.amazon.com/s3/storage-classes/
- [ ] https://aws.amazon.com/sagemaker/
- [x] https://aws.amazon.com/savingsplans/
- [ ] https://aws.amazon.com/sns/
- [ ] https://aws.amazon.com/security/
- [ ] https://aws.amazon.com/security/penetration-testing/
- [ ] https://aws.amazon.com/serverless/
- [x] https://aws.amazon.com/shield/
- [ ] https://aws.amazon.com/snowball/
- [ ] https://aws.amazon.com/snowmobile/
- [x] https://aws.amazon.com/storagegateway/
- [x] https://aws.amazon.com/systems-manager/
- [ ] https://aws.amazon.com/tco-calculator/
- [ ] https://aws.amazon.com/types-of-cloud-computing/
- [ ] https://aws.amazon.com/tools/
- [x] https://aws.amazon.com/vpc/
- [ ] https://aws.amazon.com/vpn/
- [x] https://aws.amazon.com/waf/ 
- [x] https://aws.amazon.com/waf/features/
- [ ] https://aws.amazon.com/whitepapers/designing-fault-tolerant-applications/
- [ ] https://d1.awsstatic.com/whitepapers/architecture/AWS_Well-Architected_Framework.pdf
- [ ] https://d1.awsstatic.com/whitepapers/AWS_Cloud_Best_Practices.pdf
- [ ] https://d1.awsstatic.com/whitepapers/aws_pricing_overview.pdf
- [ ] https://d1.awsstatic.com/whitepapers/cost-optimization-right-sizing.pdf
- [ ] https://d1.awsstatic.com/whitepapers/Security/AWS_Security_Best_Practices.pdf
- [ ] https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-simple-step.html
- [ ] https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html
- [ ] https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchConfiguration.html
- [x] https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html
- [ ] https://docs.aws.amazon.com/autoscaling/ec2/userguide/schedule_time.html
- [ ] https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/configurecostallocreport.html
- [ ] https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/consolidated-billing.html
- [ ] https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html
- [ ] https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/ri-behavior.html
- [ ] https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/on-demand-streaming-video.html
- [ ] https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-choosing-signed-urls-cookies.html
- [ ] https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-cookies.html
- [ ] https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html
- [ ] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html
- [ ] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html
- [ ] https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
- [x] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html
- [ ] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html
- [ ] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIT.html
- [ ] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html
- [ ] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/gsg/S3-gsg-CommonUseScenarios.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/cloudtrail-logging.html#cloudtrail-logging-%20s3-info
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/cloudwatch-monitoring.html#s3-request-cloudwatch-metrics
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html#example-scenarios-cors
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeletingObjectVersions.html#delete-obj-version-enabled-bucket-rest
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html#example-bucket-policies-use-case-4
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-transition-general-considerations.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/LogFormat.html
- [x] https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/restoring-objects.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-bucket-user-policy-specifying-principal-intro.html
- [x] https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-access-control.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html#server-access-logging-overview
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html#PresignedUrlUploadObject-LimitCapabilities
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#object-metadata
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteAccessPermissionsReqd.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel
- [ ] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.StorageReliability.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/AmazonEBS.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/concepts.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/InstanceStorage.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/dedicated-hosts-overview.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSPerformance.html#tips
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html#EBSVolumeTypes_gp2
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#launch-templates-as
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html
- [ ] https://docs.aws.amazon.com/config/latest/developerguide/gs-console.html
- [ ] https://docs.aws.amazon.com/config/latest/developerguide/how-does-config-work.html
- [ ] https://docs.aws.amazon.com/directconnect/latest/UserGuide/direct-connect-gateways.html
- [ ] https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/applications-sourcebundle.html
- [ ] https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-monitoring.html
- [ ] https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/what-is-load-balancing.html
- [ ] https://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html
- [x] https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys
- [ ] https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html
- [ ] https://docs.aws.amazon.com/health/latest/ug/getting-started-phd.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_access-advisor.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_groups.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-service.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html
- [ ] https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html
- [ ] https://docs.aws.amazon.com/lambda/latest/dg/lambda-invocation.html
- [ ] https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html
- [ ] https://docs.aws.amazon.com/opsworks/latest/userguide/best-practices-storage.html
- [ ] https://docs.aws.amazon.com/organizations/latest/APIReference/Welcome.html
- [ ] https://docs.aws.amazon.com/organizations/latest/userguide/orgs_introduction.html
- [ ] https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_create.html
- [ ] https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html
- [ ] https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover.html
- [ ] https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html
- [ ] https://docs.aws.amazon.com/snowball/latest/developer-guide/using-ec2.html#ec2-overview-edge
- [ ] https://docs.aws.amazon.com/snowball/latest/developer-guide/specifications.html#specs-v3s-optimized
- [ ] https://docs.aws.amazon.com/sns/latest/dg/channels-sms-us-requirements.html
- [ ] https://docs.aws.amazon.com/storagegateway/latest/userguide/WhatIsStorageGateway.html
- [ ] https://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html
- [x] https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html
- [x] https://docs.aws.amazon.com/vpc/latest/privatelink/concepts.html
- [x] https://docs.aws.amazon.com/vpc/latest/privatelink/gateway-endpoints.html#vpc-endpoints-limitations
- [x] https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-access.html#vpc-endpoint-policies
- [x] https://docs.aws.amazon.com/vpc/latest/tgw/tgw-nacls.html
- [x] https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-authentication-access-control.html
- [x] https://docs.aws.amazon.com/vpc/latest/userguide/how-it-works.html
- [x] https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html
- [x] https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html
- [x] https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html#nat-gateway-basics
- [x] https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html
- [x] https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Security.html#VPC_Security_Comparison
- [x] https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html
- [x] https://docs.aws.amazon.com/vpc/latest/userguide/working-with-vpcs.html#add-ipv4-cidr
- [ ] https://docs.aws.amazon.com/whitepapers/latest/aws-best-practices-ddos-resiliency/mitigation-techniques.html
- [ ] https://docs.aws.amazon.com/whitepapers/latest/aws-overview/six-advantages-of-cloud-computing.html
- [ ] https://docs.aws.amazon.com/whitepapers/latest/aws-privatelink/aws-privatelink.html
- [ ] https://docs.aws.amazon.com/whitepapers/latest/cost-optimization-reservation-models/standard-vs-convertible-offering-classes.html
- [ ] https://docs.aws.amazon.com/whitepapers/latest/how-aws-pricing-works/aws-pricingtco-tools.html
- [ ] https://docs.aws.amazon.com/whitepapers/latest/real-time-communication-on-aws/high-availability-and-scalability-on-aws.html
- [ ] https://quicksight.aws.amazon.com/
- [ ] https://media.amazonwebservices.com/AWS_TCO_Web_Applications.pdf
- [ ] https://wa.aws.amazon.com/wat.concept.edge-location.en.html 
- [ ] https://wa.aws.amazon.com/wat.concept.elasticity.en.html 
- [ ] https://wa.aws.amazon.com/wellarchitected/2020-07-02T19-33-23/wat.concept.horizontal-scaling.en.html

Optional
-------------
- [ ] https://docs.aws.amazon.com/vpc/latest/privatelink/aws-services-privatelink-support.html
- [ ] https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html
- [ ] https://docs.aws.amazon.com/vpc/latest/userguide/managed-prefix-lists.html
- [ ] https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html
- [ ] https://docs.bitnami.com/google-templates/singletier-vs-multitier/
- [ ] https://docs.aws.amazon.com/streams/latest/dev/key-concepts.html
- [ ] https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_examples.html#example-ec2-instances
- [ ] https://aws.amazon.com/premiumsupport/knowledge-center/public-load-balancer-private-ec2/
- [ ] https://aws.amazon.com/kinesis/
- [ ] https://docs.aws.amazon.com/lambda/latest/dg/invocation-scaling.html
- [ ] https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-configuring.html
- [ ] https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html
- [ ] https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scale-based-on-demand.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-scheduled-instances.html
- [ ] https://docs.aws.amazon.com/global-accelerator/latest/dg/what-is-global-accelerator.html
- [ ] https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PriceClass.html
- [ ] https://aws.amazon.com/global-accelerator/faqs/
- [ ] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
- [ ] https://aws.amazon.com/ec2/pricing/
- [ ] https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/encrypt-an-existing-amazon-rds-for-postgresql-db-instance.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html
- [x] https://aws.amazon.com/ec2/autoscaling/faqs/
- [x] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-copy-snapshot.html
- [x] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-restoring-volume.html
- [x] https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/Welcome.html
- [x] https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-cloudwatch-metrics.html
- [x] https://docs.aws.amazon.com/autoscaling/plans/userguide/what-is-a-scaling-plan.html
- [x] https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-db-encryption.html
- [x] https://aws.amazon.com/blogs/big-data/encrypt-your-amazon-redshift-loads-with-amazon-s3-and-aws-kms/
- [x] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-reserved-instances.html
- [x] https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html
- [x] https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html
- [x] https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scale-based-on-demand.html
- [x] https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-groups.html#asg-purchase-options
- [x] https://aws.amazon.com/premiumsupport/knowledge-center/organizations-move-accounts/
- [ ] VPC Connectivity Whitepaper - https://docs.aws.amazon.com/whitepapers/latest/aws-vpc-connectivity-options/welcome.html
- [ ] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html
